name: cluster_ckmeans_1d_dp
description: A Dart port of the Ckmeans.1d.dp clustering algorithm. 
version: 1.0.0
repository: https://github.com/jheyne/cluster_ckmeans_1d_dp
license: LGPL-3.0

environment:
  sdk: ^3.10.0

dependencies:
  intl: ^0.20.2

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
